# Form implementation generated from reading ui file 'c:\Users\Jule\Desktop\HastaKayitSistemi\istatistik.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(206, 528)
        Dialog.setAutoFillBackground(True)
        Dialog.setStyleSheet("QMainWindow {\n"
"    background-color: #EAF4FF;\n"
"}")
        self.label = QtWidgets.QLabel(parent=Dialog)
        self.label.setGeometry(QtCore.QRect(20, 0, 151, 16))
        font = QtGui.QFont()
        font.setBold(True)
        self.label.setFont(font)
        self.label.setStyleSheet("QLineEdit {\n"
"    background-color: lightblue;\n"
"}")
        self.label.setObjectName("label")
        self.btn_Kapat = QtWidgets.QPushButton(parent=Dialog)
        self.btn_Kapat.setGeometry(QtCore.QRect(60, 480, 81, 26))
        self.btn_Kapat.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.btn_Kapat.setObjectName("btn_Kapat")
        self.groupBox_Genel = QtWidgets.QGroupBox(parent=Dialog)
        self.groupBox_Genel.setGeometry(QtCore.QRect(10, 20, 171, 221))
        self.groupBox_Genel.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.groupBox_Genel.setAutoFillBackground(True)
        self.groupBox_Genel.setObjectName("groupBox_Genel")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_Genel)
        self.verticalLayout.setObjectName("verticalLayout")
        self.splitter = QtWidgets.QSplitter(parent=self.groupBox_Genel)
        self.splitter.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.splitter.setObjectName("splitter")
        self.label_Toplam = QtWidgets.QLabel(parent=self.splitter)
        self.label_Toplam.setObjectName("label_Toplam")
        self.label_Yatan = QtWidgets.QLabel(parent=self.splitter)
        self.label_Yatan.setObjectName("label_Yatan")
        self.label_Taburcu = QtWidgets.QLabel(parent=self.splitter)
        self.label_Taburcu.setObjectName("label_Taburcu")
        self.label_Poliklinik = QtWidgets.QLabel(parent=self.splitter)
        self.label_Poliklinik.setObjectName("label_Poliklinik")
        self.label_Erkek = QtWidgets.QLabel(parent=self.splitter)
        self.label_Erkek.setObjectName("label_Erkek")
        self.label_Kadin = QtWidgets.QLabel(parent=self.splitter)
        self.label_Kadin.setObjectName("label_Kadin")
        self.label_OrtalamaYas = QtWidgets.QLabel(parent=self.splitter)
        self.label_OrtalamaYas.setObjectName("label_OrtalamaYas")
        self.verticalLayout.addWidget(self.splitter)
        self.groupBox_Kan = QtWidgets.QGroupBox(parent=Dialog)
        self.groupBox_Kan.setGeometry(QtCore.QRect(10, 260, 171, 201))
        self.groupBox_Kan.setObjectName("groupBox_Kan")
        self.textEdit_KanGruplari = QtWidgets.QTextEdit(parent=self.groupBox_Kan)
        self.textEdit_KanGruplari.setGeometry(QtCore.QRect(10, 20, 151, 171))
        self.textEdit_KanGruplari.setReadOnly(True)
        self.textEdit_KanGruplari.setObjectName("textEdit_KanGruplari")
        self.groupBox_Kan.raise_()
        self.groupBox_Genel.raise_()
        self.label.raise_()
        self.btn_Kapat.raise_()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "📊 HASTA İSTATİSTİKLERİ"))
        self.btn_Kapat.setText(_translate("Dialog", "Kapat"))
        self.groupBox_Genel.setTitle(_translate("Dialog", "Genel Bilgiler"))
        self.label_Toplam.setText(_translate("Dialog", "Toplam Hasta"))
        self.label_Yatan.setText(_translate("Dialog", "Yatan"))
        self.label_Taburcu.setText(_translate("Dialog", "Taburcu"))
        self.label_Poliklinik.setText(_translate("Dialog", "Poliklinik Sayısı"))
        self.label_Erkek.setText(_translate("Dialog", "Erkek"))
        self.label_Kadin.setText(_translate("Dialog", "Kadın"))
        self.label_OrtalamaYas.setText(_translate("Dialog", "Ortalama Yaş"))
        self.groupBox_Kan.setTitle(_translate("Dialog", "Kan Grupları"))
